before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
      - arm
    goarm:
      - "5"
      - "6"
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w

checksum:
  name_template: "checksums.txt"
# signs:
# - cmd: cosign
#   env:
#   - COSIGN_EXPERIMENTAL=1
#   certificate: '${artifact}.pem'
#   output: true
#   artifacts: checksum
#   args:
#     - sign-blob
#     - '--output-certificate=${certificate}'
#     - '--output-signature=${signature}'
#     - '${artifact}'
