name: goreleaser

on:
  push:
    tags:
      - "v*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 4

      - name: Build and push
        uses: docker/bake-action@master
        with:
          targets: artifact-all
          push: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Move artifacts
        shell: bash
        run: |
          find ./dist -name *.json* -type f -exec rm -f {} \;
          mv -f ./dist/**/* ./dist/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
